// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/accounting-clutter/ComplexPOS.tsx": () => import("../components/mockups/accounting-clutter/ComplexPOS.tsx"),
  "./components/mockups/accounting-clutter/DashboardChaos.tsx": () => import("../components/mockups/accounting-clutter/DashboardChaos.tsx"),
  "./components/mockups/accounting-clutter/LegacyERP.tsx": () => import("../components/mockups/accounting-clutter/LegacyERP.tsx"),
  "./components/mockups/accounting-clutter/MobileLedger.tsx": () => import("../components/mockups/accounting-clutter/MobileLedger.tsx"),
  "./components/mockups/accounting-clutter/ReportOverload.tsx": () => import("../components/mockups/accounting-clutter/ReportOverload.tsx"),
  "./components/mockups/tarseed-real-glimpses/AIChat.tsx": () => import("../components/mockups/tarseed-real-glimpses/AIChat.tsx"),
  "./components/mockups/tarseed-real-glimpses/AIJournal.tsx": () => import("../components/mockups/tarseed-real-glimpses/AIJournal.tsx"),
  "./components/mockups/tarseed-real-glimpses/Dashboard.tsx": () => import("../components/mockups/tarseed-real-glimpses/Dashboard.tsx"),
  "./components/mockups/tarseed-real-glimpses/Invoice.tsx": () => import("../components/mockups/tarseed-real-glimpses/Invoice.tsx"),
  "./components/mockups/tarseed-real-glimpses/Reports.tsx": () => import("../components/mockups/tarseed-real-glimpses/Reports.tsx"),
  "./components/mockups/wudooh-dashboard/Current.tsx": () => import("../components/mockups/wudooh-dashboard/Current.tsx"),
  "./components/mockups/wudooh-dashboard/Direction.tsx": () => import("../components/mockups/wudooh-dashboard/Direction.tsx")
};
